### ISSUE TITLE
Canvas doesn't track quick click and drags

### ISSUE THREAD

**Issue by jazibobs** [jakubfiala/atrament.js#1]
I was playing with your demopage - http://fiala.uk/atrament.js/demo/ -  and noticed that when I try to draw lines quickly (e.g. I tried to draw a horizontal line quickly from one side canvas to another) the line stops after around only 100px or so.

**Comment by jakubfiala** [comment]
hey, thanks, I'm aware of this issue – it's probably because of the adaptive filtering, I'll fiddle with the params and fix it asap.

**Comment by jakubfiala** [comment]
Ok, I didn't completely remove this behaviour, as it's inherent in the smoothing filter – if you move too fast, the filter will not be fast enough to catch up. However, I did lower the smoothing limit, so now the line shouldn't stop too soon. Only pushed to master for now, as I don't want to make releases for these hotfixes. Thanks for pointing it out!
