### ISSUE TITLE
unexpected token '('

### ISSUE THREAD

**Issue by loucapo** [jakubfiala/atrament.js#10]
i'm not sure where to look so I thought I would post it here. I am using atrament in my app and it works fine in chrome and firefox but in safari its giving me a strange error:

unexpected token '('

at this line:

set(x, y) {

in Point

any ideas?

**Comment by jakubfiala** [comment]
Hi, it seems like you're using the ES6 source script located at `src/atrament.js`. This won't run in Safari yet because it doesn't support ES6 syntax.

It's best to use the `dist/atrament.min.js` file, as that's transpiled and minified.

**Comment by loucapo** [comment]
I had a feeling it was the ES6 thing. But then I saw it worked for your demo page and that confused me. I guess I incorrectly assumed dist and src were the same version; just dist was minified. Either way, its working now so thanks!
