### ISSUE TITLE
When moving mouse fast the line becomes humongous

### ISSUE THREAD

**Issue by jordyvandomselaar** [jakubfiala/atrament.js#11]
As the title says.
When I move my mouse slowly the line is very thin, but when I move it faster it becomes HUGE! How can I fix this?

**Comment by jakubfiala** [comment]
Hey, thanks for letting me know. Got any screenshots of what you mean? The line is meant to get thicker based on mouse speed, in order to create a more realistic "ink-like" look. But it shouldn't be a massive difference.

Have you, by any chance, got an unusual mouse or display? Like a hi-dpi mouse?

**Comment by jordyvandomselaar** [comment]
Image: http://prntscr.com/c5v0bz, would it be possible to turn this effect off?
I'm using a regular mouse but the app I'm using this in will get deployed on Ipads

**Comment by jakubfiala** [comment]
Thanks! It would indeed be possible to switch it off, and it's definitely an useful option. I can probably  add it by the end of the week, but please feel free to submit a PR!

**Comment by jordyvandomselaar** [comment]
Thank you! I'll see what I can do :D

**Comment by teacoat** [comment]
Hey any word on this?

**Comment by jakubfiala** [comment]
@teacoat completely forgot about this. I think I've got a nice bunch of updates lined up already, so might fix this and make a release soon.

**Comment by jakubfiala** [comment]
@jordyvandomselaar @teacoat this is now fixed in `v.0.2.3`, available on npm right now 💥

to disable the adaptive stroke width, you can just do:
```js
myAtramentInstance.adaptiveStroke = false;
```

**Comment by jordyvandomselaar** [comment]
You're awesome!

**Comment by teacoat** [comment]
@jakubfiala Just saw this, thanks a lot!
