### ISSUE TITLE
with Touch, line is away from where finger presses

### ISSUE THREAD

**Issue by javismiles** [jakubfiala/atrament.js#19]
Great library, when  I use it with mouse it's perfect. But when I use it with Touch, the line doesn't appear right where the finger presses, it appears below, but quite a bit below, which is very odd, why is the line not appearing right where the finger presses? I'm using Chrome browser in both Desktop PC and Android phone, same problem in both, latest versions of all

best wishes

**Comment by Ben76** [comment]
I am having the same problem. Is there a resolution to this problem? Works beautifully on a PC, problem noticed only on android phone only (chrome as well as firefox)
