### ISSUE TITLE
export as module

### ISSUE THREAD

**Issue by reccanti** [jakubfiala/atrament.js#2]
It doesn't look like this exports Atrament as a module. It would make it a lot easier to bundle it using tools like browserify or webpack.

**Comment by jakubfiala** [comment]
indeed it doesn't, I just used the npm stuff to have a build system. Will definitely get around to running it through webpack at some point, but PRs are also most welcome!

**Comment by reccanti** [comment]
I made a fork of the project and have been working on making an exportable bundle using webpack. I got the basics of it working on a branch called [feature-modules](https://github.com/reccanti/atrament.js/tree/feature-modules). I want to touch it up a bit more before submitting the pull request.

**Comment by jakubfiala** [comment]
Awesome, looks great. I think together with #4 this could be a good amount of changes for a new release.

**Comment by jakubfiala** [comment]
Closing this now, thanks @reccanti for webpacking this in #7 🎉
