### ISSUE TITLE
Bug on Edge Browser, after changing to a new color, and then drawing, the color picker opens when mouse is released

### ISSUE THREAD

**Issue by javismiles** [jakubfiala/atrament.js#20]
Bug on Edge Browser: If I click on color input area and change to a new color, and immediately I go to draw, when I release the mouse the color picker opens again, I draw and when I release mouse, the color picker opens again, this happens on Microsoft Edge Browser

**Comment by jakubfiala** [comment]
@javismiles thanks for letting me know, this sounds like an issue with Edge implementation of the colour input field, which I have no control of. Also I assume this affects the demo only, so you could probably get around it when you build your own application with Atrament. Going to have to close this I'm afraid.
