### ISSUE TITLE
Using 'fill' tool on a section that is already filled crashes browser tab

### ISSUE THREAD

**Issue by ianschmitz** [jakubfiala/atrament.js#22]
Easy enough to repro:

1. Open demo at [http://fiala.uk/atrament.js/demo/](url)
2. Select 'fill' tool
3. Fill the canvas by clicking on the page
4. Fill again by clicking on the page
5. Notice the crash!

**Comment by jakubfiala** [comment]
@ianschmitz thanks for flagging this up, seems like I haven't thought about the possibility of refilling with the same colour when testing :) gonna get rid of this nasty infinite loop asap.

**Comment by jakubfiala** [comment]
@ianschmitz fyi this may be fixed in #24
