### ISSUE TITLE
saving and opening a drawing

### ISSUE THREAD

**Issue by melonista** [jakubfiala/atrament.js#27]
Hi,

I am not sure is this is a bug or not, but when I save a drawing, I cannot open it with the default image viewer of windows (Windows 10). However  I can open it with MS paint and others. Therefore I wonder if there is something wrong with the generated image.

I get the image using the `toimage()` method and then I use python to save the generated image as:

```
with open("imageToSave2.png", "wb") as f:
    f.write(image_string[22:].decode('base64'))
```
I have followed this method to save the images generated by other JS drawing libraries, and I can open them with the windows image viewer.

**Comment by jakubfiala** [comment]
hey, so the `toImage` method simply wraps the [toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) method of the canvas. Not to say that this is not a valid issue, but I wonder if this has something to do with the browser implementation of the canvas method.

**Comment by melonista** [comment]
I see, the other library that I tested is https://github.com/Leimi/drawingboard.js. For some reason theirs seem to work with the windows image viewer, but it seems they are just also wrapping toDataURL.
