### ISSUE TITLE
Clarify how to access Atrament class

### ISSUE THREAD

**Issue by raphinesse** [jakubfiala/atrament.js#31]
It should be clarified that `Atrament` will never be exposed automatically. From the docs, I expected it to be in global scope, when including `atrament.min.js`.

Do not get me wrong though, I think it is good that there is only one global. This is just about clear documentation.

**Comment by jakubfiala** [comment]
This is actually a bug, `Atrament` should be exposed when you include the lib in a script tag. Thanks for flagging this up!

**Comment by raphinesse** [comment]
You're welcome

**Comment by jakubfiala** [comment]
Hi @raphinesse - just FYI, in Atrament 1.0.0 the `Atrament` class is the default export, I got rid of the factory function.
