### ISSUE TITLE
Accept options object in constructor

### ISSUE THREAD

**Issue by raphinesse** [jakubfiala/atrament.js#32]
I guess it would be far more useful to have a signature like this

```js
atrament(canvas, options)
```

where the second parameter is an object with properties corresponding to the publicly available properties on `Atrament` instances (according to the docs, that would include `weight`, `color`, `smoothing`, `adaptiveStroke`, `mode` and `opacity`) plus `width` and `height` (Even if I'd argue that you don't really need these last two. They're easily enough configured through the canvas element itself).

**Comment by jakubfiala** [comment]
@raphinesse thanks for the suggestion! I agree completely that such a signature would work better. It is an API-breaking change, so I'm going to flag this for v0.3.0.

Please do submit PRs if you can.

**Comment by jakubfiala** [comment]
stupid me, I meant to say v1.0.0

**Comment by raphinesse** [comment]
It doesn't have to be breaking. You could still support the old API and deprecate it. Something along the lines of:

```js
function atrament(canvas, options) {
  if (typeof options === 'number') {
    console.warn('Calling style deprecated. Use new style instead. [Further information]')
    // convert old style arguments to options object
  }
  // Use new options object
}
```
