### ISSUE TITLE
Single input is sometimes ignorned

### ISSUE THREAD

**Issue by BillyBlaze** [jakubfiala/atrament.js#33]
If you want to draw a single dot, then sometime the input get's ignored. (maybe because mousemove doesnt trigger?) See the attachment for a screen grab.

![input-eaten](https://user-images.githubusercontent.com/445608/26967156-7b58e9d2-4cfd-11e7-9e85-c458a24a4a05.gif)

Browsers affected: Chrome, Firefox, MS edge

**Comment by jakubfiala** [comment]
thanks for the heads up! will look into it as soon as I can, otherwise feel free to submit a PR if you know how to fix this 😉
