### ISSUE TITLE
Unable to save the canvas background color.

### ISSUE THREAD

**Issue by Ben76** [jakubfiala/atrament.js#35]
I am trying to save the canvas along with its background color and use it elsewhere to prepare a collage. But, I only get to see a black background. Any help to get this resolved greatly appreciated.
Regards

**Comment by jakubfiala** [comment]
hey @Ben76, thanks for submitting an issue! how are you creating the background colour? The canvas should be transparent by default, so you need to draw a `fillRect(0, 0, canvas.width, canvas.height)` first.

**Comment by jakubfiala** [comment]
closing this issue as it hasn't been active for a few years
