### ISSUE TITLE
Fill bucket doesn't work on mobile chrome

### ISSUE THREAD

**Issue by rubenanton90** [jakubfiala/atrament.js#37]
Steps to reproduce:

- Open the demo at [http://fiala.uk/atrament.js/demo/](http://fiala.uk/atrament.js/demo/) on chrome mobile
- Try to use the fill mode, either applied to the whole picture, or to a region delimited by a stroke. Nothing happens.

Tested on Samsung Galaxy S7 and Google Nexus 5 devices.

(As a side note, I couldn't get the demo working at all on Firefox Mobile)

Thank you

**Comment by jakubfiala** [comment]
@rubenanton90 thanks for the issue! I don't currently have access to an android device but might get hold of a simulator to test.

Have you noticed any errors in the console?

**Comment by rubenanton90** [comment]
Ok, I tested on both the demo site and the project I'm working on (Cordova/Ionic 3, using Chrome WebView)
On the demo site, there's no error message and the bucket never works, debugger or not.

On my Ionic project, interestingly enough, if the chrome debugger is active on the device the fill bucket actually works! When it's working, the console complains about this, though:

![imagen](https://user-images.githubusercontent.com/1357400/41287055-d4ccf146-6e41-11e8-8f88-fabb2fe0bf89.png)
_Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted._

Once you disconnect the debugger it fails again though.
