### ISSUE TITLE
Erase does not work

### ISSUE THREAD

**Issue by davidlr99** [jakubfiala/atrament.js#47]
I tried to change the drawing mode to` sketcher.mode = 'erase'` - does not seem to work in the new version.
Its also not working in your demo anymore: http://fiala.uk/atrament.js/demo/

**Comment by jakubfiala** [comment]
thanks for the heads up @davidlr99. I feel like I'm gonna have to write some tests at some point.. will fix the erase function in the next update ASAP.

**Comment by jakubfiala** [comment]
Hi @davidlr99 - this should now be fixed in [v1.1.0](https://github.com/jakubfiala/atrament.js/releases/tag/v.1.1.0). Feel free to reopen if you still encounter issues.
