### ISSUE TITLE
Add a "disable" option for drawing mode.

### ISSUE THREAD

**Issue by uriberto** [jakubfiala/atrament.js#60]
It might be convenient to have a sketchpad open but disable drawing. For example, maybe some users are allowed to draw and others can see the drawing (via syncing the strokes in realtime) but those users should not be able to draw themselves. For example, that could be useful for a virtual blackboard. It'd be nice to set their sketchpad to "disabled" mode. I think this only requires adding the option of "disabled" and no extra code for it, since you're already checking mode on every stroke.

**Comment by jakubfiala** [comment]
@uriberto thank you for your contribution, this feature has now been shipped in [https://github.com/jakubfiala/atrament.js/releases/tag/v1.3.0](url)
