### ISSUE TITLE
question about layers/transparency

### ISSUE THREAD

**Issue by ndmetrick** [jakubfiala/atrament.js#74]
We're a group of students looking for a drawing library to use for a game we're making, and we love Atrament, but we need something that will save the drawing on a transparent background so we don't have the white square of canvas. I didn't know if there was a way to do that using Atrament, but thought I'd ask.

**Comment by ndmetrick** [comment]
I don't know why I thought it didn't automatically do this...but we figured it out.

**Comment by jakubfiala** [comment]
@ndmetrick thank you for reaching out! yes indeed Atrament simply draws on top of whatever is on the canvas, so by default that's a transparent background. Glad to hear you're using Atrament for your game, I'd be happy to check it out if you want :)
