### ISSUE TITLE
Different behavior when Inspect Element is open on Chrome

### ISSUE THREAD

**Issue by ztw0** [jakubfiala/atrament.js#83]
Hi, I can't help but notice a difference when using Atrament with and without Inspect Element open on Chrome. It isn't a big issue, but is there a reason for this?

In this picture, the above is written with inspect open, and bottom is without. The above is more rough, and has 0 smoothing lag when writing, where as the version below (the one people will use) behaves properly.
![image](https://user-images.githubusercontent.com/6711534/210900609-edf266de-6041-4eee-aa3c-d3080c4bacf1.png)

I tried on this website: https://www.fiala.space/atrament.js/demo/

**Comment by jakubfiala** [comment]
@ztw0 thank you for reporting the issue! I'll look into it this coming Monday.

**Comment by jakubfiala** [comment]
@ztw0 I'm afraid I couldn't reproduce the issue (using Chromium on Ubuntu). What OS/Chrome version are you using?

**Comment by ztw0** [comment]
@jakubfiala  Chrome Version 97.0.4692.71 on Windows 10
It isn't a big issue, as it only happens when inspect element is open. I think it records more points which leads to this behavior. Great library nonetheless!
